# Generated by Django 5.1.4 on 2025-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_options_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='media/products', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='media/avatars', verbose_name='Аватар'),
        ),
    ]
