name: 'coverage'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Python Coverage 
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: orders/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
